/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "app.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

wyjscie *
obliczenia_1(wejscie *argp, CLIENT *clnt)
{
	static wyjscie clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, OBLICZENIA,
		(xdrproc_t) xdr_wejscie, (caddr_t) argp,
		(xdrproc_t) xdr_wyjscie, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
