/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "app.h"

bool_t
xdr_wejscie (XDR *xdrs, wejscie *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_wyjscie (XDR *xdrs, wyjscie *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->suma))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->roznica))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->iloczyn))
		 return FALSE;
	return TRUE;
}
